/**
 *  A Visualisation Tool for 
 *  Selection Hyper-Heuristics                                    <br>   
 *  															  <br>
 *  http://code.google.com/p/vch/   							  <br>
 *  															  <br>
 *  Module:                  G52GRP, University of Nottingham     <br>
 *  															  <br>
 *  Group:        gp09-exo    						  			  <br>
 * @author 	   	Lao Jingqi (jxl29u)
 * @author	   	Zhang Chao (cxz09u)
 * @author		Thomas Barton (txb18u)
 * @author		Ben Jenkinson (bxj08u)
 * @author	   	Alexander Jermstad (asj08u) 
 * 			
 */

/**
 *  This class abstract the methods of benchmark function.
 */
public abstract class Function {
	/**
	 * return the concrete  function's name
	 * @return the concrete  function's name
	 */
	abstract String getName();
	/**
	 * evaluate the binary representing value by applying the concrete function
	 * @param bit 
	 * @return the value generated by the function
	 */
	abstract double evaluate(int[] bit);
	/**
	 * evaluate integer value by applying the concrete function
	 * @param x
	 * @return the value generated by the function
	 */
	abstract double evaluateInteger(int x);
}
